version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vistapro_local_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vistapro_local
      POSTGRES_PASSWORD: local_dev_password
      POSTGRES_DB: vistapro_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_dump:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vistapro_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: vistapro_local_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: vistapro_network
