services:
  - type: web
    name: vistapro-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vistapro-db
          property: connectionString
    healthCheckPath: /api/health
