version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: vistapro_postgres
    environment:
      POSTGRES_DB: vistapro_dev
      POSTGRES_USER: vistapro_user
      POSTGRES_PASSWORD: vistapro_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vistapro_user -d vistapro_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vistapro_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vistapro.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
